flag:
  commands:
    command:
      default: true
      type: whitelist
      list:
        - login
        - register
        - msg
        - list
        - r
        - sethome
tp-owner-only: true
christmas:
  enable: false
  year: 2016
  month: 12
  day: 24
  hour: 17
  minute: 30
debug: false
file_version: 0.3