name: ResPlus
author: Genhis
website: http://genhis.6f.sk/
depend: [GLib, Residence]
softdepend: [AuthMe, ChestShop, MagicCarpet]
main: sk.genhis.resplus.ResPlus
version: ${project.version}
api-version: 1.14